version: "3.8"

services:
  app:
    container_name: finance-control-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    container_name: finance-control-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance_control
    ports:
      - "5432:5432"
    volumes:
      - "/data/postgres:/var/lib/postgresql/data"
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0

    volumes:
      - "/ollama-data:/root/.ollama" # Shared volume for models
    ports:
      - "11434:11434"

volumes:
  postgres_data:
